config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"


  devise_for :users

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following
      get :followers
    end
  end

  resources :relationships, only: [:create, :destroy]  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :title, presence: true 
  validates :body, presence: true, length: {maximum: 200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(method, word)
    case method
    when "perfect"
      where(title: word)
    when "forward"
      where("title LIKE ?", "#{word}%")
    when "backward"
      where("title LIKE ?", "%#{word}")
    when "partial"
      where("title LIKE ?", "%#{word}%")
    end
  end

  def self.search_for(word, method)
    case method
    when 'perfect'
      where(title: word)
    when 'forward'
      where('title LIKE ?', "#{word}%")
    when 'backward'
      where('title LIKE ?', "%#{word}")
    when 'partial'
      where('title LIKE ?', "%#{word}%")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    #@users = User.all
    @user = User.find(current_user.id)
  end

  def show
    @Bookshow = Book.new
    @book = Book.find(params[:id])
    @user = User.find(current_user.id)
    @book_comment = BookComment.new
  end

    # 投稿データの保存
    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save!
        flash[:success] = "Post was successfully"
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        @user = User.find(current_user.id)
        render :index
      end
    end

    def edit
      @book = Book.find(params[:id])
      unless @book.user == current_user
       redirect_to books_path
      end
    end

    def update
      @book = Book.find(params[:id])
      @book.update(book_params)
      # flash[:success] = "Edit was successfully"
      # redirect_to book_path(book.id)  
      if @book.save!
        flash[:success] = "Edit was successfully"
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end

    def destroy
      book = Book.find(params[:id])
      book.destroy
      flash[:success] = "Book was successfully Destroyed."
      redirect_to '/books'
    end

    # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<h1>User info</h1>
<table>
  <tr>
    <th><%= image_tag user.get_profile_image(100,100) %></th>
  </tr>
  <tr>
    <td>name:</td>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <td>introduction:</td>
    <td><%= user.introduction %></td>
  </tr>
  <tr>
    <td>
    <% if user.id == current_user.id %>
      <%= link_to edit_user_path(user.id) do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
    </td>
  </tr>

</table>
<p>
  <%= link_to "Following: #{user.following.count}", following_user_path(user), class: "btn btn-outline-primary btn-sm d-block my-1" %>
  <%= link_to "Followers: #{user.followers.count}", followers_user_path(user), class: "btn btn-outline-primary btn-sm d-block my-1" %>
  <%= render 'users/follow_button', user: @user %>
</p>

<h1>New book</h1>
<% if book.errors.any? %> 
	<h3><%= book.errors.count %> errors occurred</h3>
	<ul>
    <% book.errors.full_messages.each do |message| %> 
				<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<%= form_with model: book, url: '/books', method: :post do |f| %>
  
  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>

  <br></br>
  <%= f.submit 'Create Book' %>
  
<% end %>

app/views/books/_comment.html.erb
<div id="comment-<%= comment.id %>" class="mb-3 p-2 border rounded">
  <%= link_to user_path(comment.user.id) do %>
    <%= image_tag comment.user.get_profile_image(100, 100), class: "rounded-circle", size: "50x50" %><br>
    <strong><%= comment.user.name %></strong>
  <% end %>
  <p><%= comment.comment %></p>

  <% if comment.user == current_user %>
    <%= link_to "Destroy", book_book_comment_path(comment.book, comment),
                method: :delete,
                remote: true,
                data: { confirm: "削除しますか？" },
                class: "btn btn-sm btn-danger mt-2" %>
  <% end %>
</div>

app/views/books/_favorite_button.html.erb
<% favorite = book.favorites.find_by(user_id: current_user.id) %>

<% if favorite.present? %>
  <%= link_to book_favorite_path(book, favorite),
              method: :delete,
              remote: true,
              id: "favorite-link-#{book.id}" do %>
    <span class="text-danger">
      <i class="fa-solid fa-heart"></i> <%= book.favorites.count %>
    </span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book),
              method: :post,
              remote: true,
              id: "favorite-link-#{book.id}" do %>
    <span class="text-primary">
      <i class="fa-regular fa-heart"></i> <%= book.favorites.count %>
    </span>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %> 
  <h3><%= @book.errors.count %> errors occurred</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %> 
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<h1>Editing Book</h1>
<%= form_with model: @book, url:book_path(@book.id), method: :patch do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>
  
  <h4>body</h4>
  <%= f.text_area :body %>
  <br></br>
  
  <%= f.submit 'Update Book' %>
  <br></br>
  
  <%= link_to "Show", book_path(@book.id) %>
  <span>|</span>
  <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% if flash[:success] %>
        <div class="success">
          <%= flash[:success] %>
        </div>
      <% end %>
      <%= render 'book', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-striped">
        <% @books.each do |book| %>
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100, 100), class: "mt-3" %>
              <% end %>
              <p class="card-title">
                <%= link_to book.title, book_path(book.id) %>
              </p>

              <p class="card-text">
                <%= book.body %>
              </p>

              <div id="favorite-button-<%= book.id %>">
                <%= render 'favorites/favorite_button', book: book %>
              </div>

              <p><%= "コメント数：#{book.book_comments.count}" %></p>
            </div>
          </div>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:success] %>
  <div class="success">
    <%= flash[:success] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', user: @book.user, book: @Bookshow %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>

      <table class="table table-striped">
        <tr>
          <td colspan="2">
            <%= link_to user_path(@book.user.id) do %>
              <%= image_tag @book.user.get_profile_image(100, 100) %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>タイトル: <%= link_to @book.title, book_path(@book.id) %></td>
          <td>本文: <%= @book.body %></td>
        </tr>
        <tr>
          <td>
            <div id="favorite-button-<%= @book.id %>">
              <%= render 'favorite_button', book: @book %>
            </div>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
        </tr>
        <% if @book.user.id == current_user.id %>
          <tr>
            <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </table>

      <div class="mb-4">
        <div id="comments">
          <%= render partial: "books/comment", collection: @book.book_comments, as: :comment %>
        </div>

        <%= form_with(model: [@book, BookComment.new], local: false, data: { turbo: false }, html: { id: "comment_form" }) do |f| %>
          <%= f.text_area :comment, class: "form-control", rows: 2 %>
          <%= f.submit "送信", class: "btn btn-primary mt-2" %>
        <% end %>                 
      </div>
    </div>
  </div>
</div>